apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: counter-frontend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
  type: NodePort