apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-db
spec:
  selector:
    matchLabels:
      app: counter-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: counter-db
    spec:
      containers:
      - image: mysql:latest
        name: counter-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: counter-db
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
